/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic_Interface;

import static Graphic_Interface.Inicio.Productos;
import static Graphic_Interface.Inicio.RutaProductos;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javapop.JavaPoP;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel González González - GISI
 */
public class ConsultarProductos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarProducto
     */
    public ConsultarProductos() {
        initComponents();
        cargaProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_Producto = new javax.swing.JComboBox<>();
        lbl_Nombre = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        lbl_Descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Descripcion = new javax.swing.JTextArea();
        lbl_Categoria = new javax.swing.JLabel();
        lbl_Estado = new javax.swing.JLabel();
        tf_Precio = new javax.swing.JTextField();
        lbl_Euro = new javax.swing.JLabel();
        lbl_Precio = new javax.swing.JLabel();
        lbl_Imagen = new javax.swing.JLabel();
        lbl_Fecha = new javax.swing.JLabel();
        lbl_Ubicacion = new javax.swing.JLabel();
        tf_Ubicacion = new javax.swing.JTextField();
        btn_Volver = new javax.swing.JButton();
        btn_Baja = new javax.swing.JButton();
        lbl_Logo = new javax.swing.JLabel();
        tf_Categoria = new javax.swing.JTextField();
        tf_Estado = new javax.swing.JTextField();
        tf_Fecha = new javax.swing.JTextField();
        lbl_Imagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaPOP - Consulta de Productos");
        setSize(new java.awt.Dimension(30, 30));

        cb_Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione producto..." }));
        cb_Producto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ProductoItemStateChanged(evt);
            }
        });

        lbl_Nombre.setText("Nombre:");

        tf_Nombre.setEditable(false);

        lbl_Descripcion.setText("Descripción:");

        ta_Descripcion.setEditable(false);
        ta_Descripcion.setColumns(20);
        ta_Descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_Descripcion);

        lbl_Categoria.setText("Categoría:");

        lbl_Estado.setText("Estado:");

        tf_Precio.setEditable(false);
        tf_Precio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tf_Precio.setText("0.00");

        lbl_Euro.setText("€");

        lbl_Precio.setText("Precio:");

        lbl_Imagen.setText("Fotografía:");

        lbl_Fecha.setText("Fecha:");

        lbl_Ubicacion.setText("Ubicación:");

        tf_Ubicacion.setEditable(false);

        btn_Volver.setText("Volver");
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });

        btn_Baja.setText("Dar de baja");
        btn_Baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BajaActionPerformed(evt);
            }
        });

        lbl_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JavaPOP_Logo.png"))); // NOI18N

        tf_Categoria.setEditable(false);

        tf_Estado.setEditable(false);

        tf_Fecha.setEditable(false);

        lbl_Imagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/noDisponible_opt.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Ubicacion)
                            .addComponent(lbl_Fecha)
                            .addComponent(lbl_Estado)
                            .addComponent(lbl_Precio)
                            .addComponent(lbl_Categoria)
                            .addComponent(lbl_Descripcion)
                            .addComponent(lbl_Nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_Precio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_Euro))
                                    .addComponent(jScrollPane1)
                                    .addComponent(tf_Nombre)
                                    .addComponent(tf_Categoria)
                                    .addComponent(tf_Estado))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_Ubicacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_Fecha))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_Producto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(btn_Baja, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Imagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Imagen1)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Baja, btn_Volver});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbl_Descripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Nombre))
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Categoria)
                            .addComponent(tf_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Estado)
                            .addComponent(tf_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Euro)
                            .addComponent(lbl_Precio))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Imagen)
                    .addComponent(lbl_Imagen1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Fecha)
                    .addComponent(tf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Ubicacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Volver)
                    .addComponent(btn_Baja))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método (botón) borra el producto seleccionado
     *
     * @param evt
     */
    private void btn_BajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BajaActionPerformed
        // TODO add your handling code here:
        Productos.remove(cb_Producto.getSelectedIndex() - 1);
        guardarProductos();
        JOptionPane.showMessageDialog(rootPane, "Producto dado de baja con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_BajaActionPerformed

    /**
     * Este método (botón) vuelve a la ventana anterior
     *
     * @param evt
     */
    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_VolverActionPerformed

    /**
     * Este método (combo box) llama al método limpiar (que vacía el texto),
     * seleccionamos un producto de la lista y llama al método cambiarTexto (que
     * nos muestra el producto)
     *
     * @param evt
     */
    private void cb_ProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ProductoItemStateChanged
        // TODO add your handling code here:
        limpiar();
        if (cb_Producto.getSelectedIndex() == 0) {
            return;
        }
        cambiarTexto();
    }//GEN-LAST:event_cb_ProductoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Baja;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JComboBox<String> cb_Producto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Categoria;
    private javax.swing.JLabel lbl_Descripcion;
    private javax.swing.JLabel lbl_Estado;
    private javax.swing.JLabel lbl_Euro;
    private javax.swing.JLabel lbl_Fecha;
    private javax.swing.JLabel lbl_Imagen;
    private javax.swing.JLabel lbl_Imagen1;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Precio;
    private javax.swing.JLabel lbl_Ubicacion;
    private javax.swing.JTextArea ta_Descripcion;
    private javax.swing.JTextField tf_Categoria;
    private javax.swing.JTextField tf_Estado;
    private javax.swing.JTextField tf_Fecha;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_Precio;
    private javax.swing.JTextField tf_Ubicacion;
    // End of variables declaration//GEN-END:variables

    /**
     * Este método carga los productos a la combo box para poder seleccionarlos
     */
    private void cargaProductos() {
        int aux = 0;
        while (aux < Productos.size()) {
            cb_Producto.addItem(Productos.get(aux).nombre);
            aux++;
        }
    }

    /**
     * Este método vacía el texto de las cajas de texto
     */
    private void limpiar() {
        ta_Descripcion.setText("");
        tf_Categoria.setText("");
        tf_Estado.setText("");
        tf_Fecha.setText("");
        tf_Nombre.setText("");
        tf_Precio.setText("");
        tf_Ubicacion.setText("");
    }

    /**
     * Este método muestra la información del producto seleccionado cambiando el
     * texto de las cajas de texto
     */
    private void cambiarTexto() {
        ta_Descripcion.setText(Productos.get(cb_Producto.getSelectedIndex() - 1).descripcion);
        tf_Categoria.setText(Productos.get(cb_Producto.getSelectedIndex() - 1).categoria);
        tf_Estado.setText(Productos.get(cb_Producto.getSelectedIndex() - 1).condicion);
        tf_Fecha.setText(Productos.get(cb_Producto.getSelectedIndex() - 1).fecha);
        tf_Nombre.setText(Productos.get(cb_Producto.getSelectedIndex() - 1).nombre);
        tf_Precio.setText(Double.toString(Productos.get(cb_Producto.getSelectedIndex() - 1).precio));
        tf_Ubicacion.setText(Productos.get(cb_Producto.getSelectedIndex() - 1).ubicacion);
    }

    /**
     * Este método guarda los productos restantes una vez se ha dado de baja
     * alguno de ellos
     */
    private void guardarProductos() {
        try {
            int i = 0;
            //Menú de la app JavaPoP
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(RutaProductos));
            while (i < Productos.size()) {
                oos.writeObject(Productos.get(i));
                i++;
            }
        } catch (IOException ex) {
            Logger.getLogger(JavaPoP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
