/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic_Interface;

import static Graphic_Interface.Inicio.Productos;
import static Graphic_Interface.Inicio.RutaProductos;
import static Graphic_Interface.Inicio.readProducts;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javapop.Cliente;
import javapop.JavaPoP;
import javapop.Producto;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Daniel González González - GISI
 */
public class AltaProductos extends javax.swing.JFrame {

    private static Cliente Cliente;

    /**
     * Creates new form AltaProductos
     */
    public AltaProductos(Cliente cliente) {
        AltaProductos.Cliente = cliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Nombre = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        lbl_Descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Descripcion = new javax.swing.JTextArea();
        lbl_Ubicacion = new javax.swing.JLabel();
        tf_Ubicacion = new javax.swing.JTextField();
        lbl_Categoria = new javax.swing.JLabel();
        btn_Cancelar = new javax.swing.JButton();
        cb_Categoria = new javax.swing.JComboBox<>();
        lbl_Estado = new javax.swing.JLabel();
        tf_Precio = new javax.swing.JTextField();
        cb_Estado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btn_Alta = new javax.swing.JButton();
        lbl_Precio = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        lbl_Foto = new javax.swing.JLabel();
        lbl_Fecha = new javax.swing.JLabel();
        tf_Fecha = new javax.swing.JTextField();
        lbl_Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaPOP - Alta de productos");

        lbl_Nombre.setText("Nombre:");

        lbl_Descripcion.setText("Descripción:");

        ta_Descripcion.setColumns(20);
        ta_Descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_Descripcion);

        lbl_Ubicacion.setText("Ubicación:");

        lbl_Categoria.setText("Categoría:");

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        cb_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoría...", "Moda y accesorios", "TV, audio y foto", "Móviles y telefonía", "Consolas y videojuegos", "Deporte y ocio" }));

        lbl_Estado.setText("Estado:");

        cb_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el estado del producto...", "Nuevo", "Como nuevo", "Bueno", "Aceptable", "Regular" }));

        jLabel5.setText("€");

        btn_Alta.setText("Dar de alta");
        btn_Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AltaActionPerformed(evt);
            }
        });

        lbl_Precio.setText("Precio:");

        lbl_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JavaPOP_Logo.png"))); // NOI18N

        lbl_Foto.setText("Fotografía:");

        lbl_Fecha.setText("Fecha:");

        lbl_Imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/noDisponible_opt.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_Descripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lbl_Categoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Estado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Precio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btn_Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Ubicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addComponent(lbl_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tf_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_Ubicacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Fecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Alta, btn_Cancelar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nombre))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Categoria))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Estado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_Precio)))
                    .addComponent(lbl_Descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Foto)
                    .addComponent(lbl_Imagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Fecha)
                    .addComponent(tf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Ubicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Alta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AltaActionPerformed
        // TODO add your handling code here:
        if (comprobar()) {
            JOptionPane.showMessageDialog(null, "Se ha registrado su producto correctamente", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            if (JOptionPane.showConfirmDialog(null, "¿Desea destacar este producto?", "Producto Destacado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null, "Se le realizará un cargo de 5€ a su tarjeta:\n" + Cliente.tjt_credito, "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
                Productos.add(new Producto(tf_Nombre.getText(), ta_Descripcion.getText(), cb_Categoria.getItemAt(cb_Categoria.getSelectedIndex()), cb_Estado.getItemAt(cb_Estado.getSelectedIndex()), Double.parseDouble(tf_Precio.getText()), tf_Fecha.getText(), tf_Ubicacion.getText(),Cliente, true));
            } else {
                Productos.add(new Producto(tf_Nombre.getText(), ta_Descripcion.getText(), cb_Categoria.getItemAt(cb_Categoria.getSelectedIndex()), cb_Estado.getItemAt(cb_Estado.getSelectedIndex()), Double.parseDouble(tf_Precio.getText()), tf_Fecha.getText(), tf_Ubicacion.getText(), Cliente));
            }
            guardarProductos();
            Productos = readProducts();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_AltaActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaProductos(Cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Alta;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JComboBox<String> cb_Categoria;
    private javax.swing.JComboBox<String> cb_Estado;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Categoria;
    private javax.swing.JLabel lbl_Descripcion;
    private javax.swing.JLabel lbl_Estado;
    private javax.swing.JLabel lbl_Fecha;
    private javax.swing.JLabel lbl_Foto;
    private javax.swing.JLabel lbl_Imagen;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Precio;
    private javax.swing.JLabel lbl_Ubicacion;
    private javax.swing.JTextArea ta_Descripcion;
    private javax.swing.JTextField tf_Fecha;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_Precio;
    private javax.swing.JTextField tf_Ubicacion;
    // End of variables declaration//GEN-END:variables

    private boolean comprobar() {
        boolean variable = true;
        if (!comprobarCategoria()) {
            variable = false;
        }
        if (!comprobarEstado()) {
            variable = false;
        }
        if (!comprobarPrecio()) {
            variable = false;
        }
        if (!comprobarFecha()) {
            variable = false;
        }
        if (ta_Descripcion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tienes que rellenar la descripción", "Error en Descripción", JOptionPane.ERROR_MESSAGE);
            variable = false;
        }
        if (tf_Nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tienes que rellenar el nombre", "Error en Nombre", JOptionPane.ERROR_MESSAGE);
            variable = false;
        }
        if (tf_Ubicacion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tienes que rellenar la ubicación", "Error en Ubicación", JOptionPane.ERROR_MESSAGE);
            variable = false;
        }
        return variable;
    }

    private boolean comprobarCategoria() {

        if (cb_Categoria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Tienes que seleccionar una categoría", "Error en Categoría", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean comprobarEstado() {
        if (cb_Estado.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Tienes que seleccionar un estado", "Error en Estado", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean comprobarPrecio() {
        try {
            double numero = Double.parseDouble(tf_Precio.getText());
            if (numero > 0) {
                return true;
            }
            JOptionPane.showMessageDialog(null, "El precio tiene que ser mayor que 0", "Error en Precio", JOptionPane.ERROR_MESSAGE);
            return false;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El precio ha de tener un formato numérico", "Error en Precio", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean comprobarFecha() {
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            Date date = format.parse(tf_Fecha.getText());
            return true;
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "El formato de fecha ha de ser: \ndd/mm/aaaa", "Formato de Fecha Erróneo", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    }

    private void guardarProductos() {
        try {
            int i = 0;
            //Menú de la app JavaPoP
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(RutaProductos));
            while (i < Productos.size()) {
                oos.writeObject(Productos.get(i));
                i++;
            }
        } catch (IOException ex) {
            Logger.getLogger(JavaPoP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
