/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic_Interface;

import static Graphic_Interface.Inicio.Ventas;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javapop.Producto;
import javapop.Venta;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel González González - GISI
 */
public class ConsultarVentas extends javax.swing.JFrame {

    public static ArrayList<Venta> VentasLocal = new ArrayList();

    /**
     * Creates new form ConsultarVenta
     */
    public ConsultarVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_Fecha = new javax.swing.ButtonGroup();
        lbl_Estado = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        tf_Categoria = new javax.swing.JTextField();
        lbl_Euros = new javax.swing.JLabel();
        lbl_Precio = new javax.swing.JLabel();
        lbl_Foto = new javax.swing.JLabel();
        lbl_FechaP = new javax.swing.JLabel();
        cb_Venta = new javax.swing.JComboBox<>();
        lbl_NombreP = new javax.swing.JLabel();
        lbl_Ubicacion = new javax.swing.JLabel();
        tf_FechaV = new javax.swing.JTextField();
        tf_Ubicacion = new javax.swing.JTextField();
        lbl_Descripcion = new javax.swing.JLabel();
        btn_Volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Descripcion = new javax.swing.JTextArea();
        lbl_Categoria = new javax.swing.JLabel();
        lbl_FechaV = new javax.swing.JLabel();
        lbl_NC = new javax.swing.JLabel();
        tf_NC = new javax.swing.JTextField();
        lbl_DNIC = new javax.swing.JLabel();
        tf_DNIC = new javax.swing.JTextField();
        tf_NV = new javax.swing.JTextField();
        lbl_NV = new javax.swing.JLabel();
        tf_DNIV = new javax.swing.JTextField();
        lbl_DNIV = new javax.swing.JLabel();
        rb_Historico = new javax.swing.JRadioButton();
        rb_Fecha = new javax.swing.JRadioButton();
        tf_Fecha = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        tf_NombreP = new javax.swing.JTextField();
        lbl_PRODUCTO = new javax.swing.JLabel();
        tf_Estado = new javax.swing.JTextField();
        tf_Precio = new javax.swing.JTextField();
        tf_FechaP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaPOP - Consultar Ventas");

        lbl_Estado.setText("Estado:");

        lbl_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JavaPOP_Logo.png"))); // NOI18N

        tf_Categoria.setEditable(false);

        lbl_Euros.setText("€");

        lbl_Precio.setText("Precio:");

        lbl_Foto.setText("Fotografía:");

        lbl_FechaP.setText("Fecha:");

        cb_Venta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione venta..." }));
        cb_Venta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_VentaItemStateChanged(evt);
            }
        });

        lbl_NombreP.setText("Nombre:");

        lbl_Ubicacion.setText("Ubicación:");

        tf_FechaV.setEditable(false);

        tf_Ubicacion.setEditable(false);

        lbl_Descripcion.setText("Descripción:");

        btn_Volver.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Volver.setText("Volver");
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });

        ta_Descripcion.setEditable(false);
        ta_Descripcion.setColumns(20);
        ta_Descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_Descripcion);

        lbl_Categoria.setText("Categoría:");

        lbl_FechaV.setText("Fecha Venta:");

        lbl_NC.setText("Nombre Comprador:");

        tf_NC.setEditable(false);

        lbl_DNIC.setText("DNI:");

        tf_DNIC.setEditable(false);

        tf_NV.setEditable(false);

        lbl_NV.setText("Nombre Vendedor:");

        tf_DNIV.setEditable(false);

        lbl_DNIV.setText("DNI:");

        btnG_Fecha.add(rb_Historico);
        rb_Historico.setSelected(true);
        rb_Historico.setText("Historico");

        btnG_Fecha.add(rb_Fecha);
        rb_Fecha.setText("Fecha:");

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        tf_NombreP.setEditable(false);

        lbl_PRODUCTO.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_PRODUCTO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_PRODUCTO.setText("PRODUCTO");

        tf_Estado.setEditable(false);

        tf_Precio.setEditable(false);

        tf_FechaP.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rb_Historico)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rb_Fecha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_Fecha))
                        .addComponent(lbl_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_Venta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_NC, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(lbl_DNIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_NV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_DNIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_FechaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_FechaV)
                                .addComponent(tf_DNIV, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_NV, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_DNIC)
                                .addComponent(tf_NC))))
                    .addComponent(btn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_NombreP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_Precio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Estado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Foto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_FechaP, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Euros, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_NombreP)
                            .addComponent(jScrollPane1)
                            .addComponent(tf_Categoria)
                            .addComponent(tf_Estado)
                            .addComponent(tf_FechaP)
                            .addComponent(tf_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_PRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_Historico)
                            .addComponent(rb_Fecha)
                            .addComponent(tf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Buscar)
                        .addGap(18, 18, 18)
                        .addComponent(cb_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_NC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_NC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_DNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DNIC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_NV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_NV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_DNIV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DNIV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_FechaV)
                            .addComponent(tf_FechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbl_PRODUCTO)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_NombreP)
                            .addComponent(tf_NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Descripcion)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Categoria)
                            .addComponent(tf_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Estado)
                            .addComponent(tf_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Precio)
                            .addComponent(lbl_Euros)
                            .addComponent(tf_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Foto)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_FechaP)
                            .addComponent(tf_FechaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Ubicacion))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método (botón) limpia las cajas de texto y permite la búsqueda de
     * ventas de dos maneras: si el usuario marca Histórico, se mostrarán todas
     * las ventas registradas, y si marca fecha, deberá introducir una fecha
     * para buscar las ventas registradas a partir de la misma
     *
     * @param evt
     */
    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
        limpiar();

        if (btnG_Fecha.isSelected(rb_Historico.getModel())) { //Si selecciona histórico, entra en el bucle

            int aux = 0;
            while (aux < Ventas.size()) {
                VentasLocal.add(Ventas.get(aux));
                cb_Venta.addItem(Ventas.get(aux).DNIComprador + " - " + Ventas.get(aux).DNIVendedor); //Se añaden todas las ventas registradas en el sistema con los DNI's de los implicados
                aux++;
            }
            JOptionPane.showMessageDialog(rootPane, "Busqueda realizada", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } else if (btnG_Fecha.isSelected(rb_Fecha.getModel())) { //Si selecciona fecha, entra en el bucle
            if (!ComprobarFecha(tf_Fecha.getText())) { //Comprobamos el formato de la fecha
                JOptionPane.showMessageDialog(rootPane, "El formato de fecha ha de ser: \ndd/mm/aaaa", "Formato de Fecha Erróneo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int aux = 0;
            while (aux < Ventas.size()) {
                if (Date(tf_Fecha.getText()).compareTo(Date(Ventas.get(aux).fechaVenta)) <= 0) { //Se compara la fecha introducida con las fechas de las ventas del sistema
                    VentasLocal.add(Ventas.get(aux));
                    cb_Venta.addItem(Ventas.get(aux).DNIComprador + " - " + Ventas.get(aux).DNIVendedor); //Se añaden todas las ventas registradas en el sistema según la fecha con los DNI's de los implicados al combo box
                }
                aux++;
            }
            JOptionPane.showMessageDialog(rootPane, "Busqueda realizada", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_BuscarActionPerformed

    /**
     * Este método (botón) sirve para volver a la ventana anterior
     *
     * @param evt
     */
    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_VolverActionPerformed

    /**
     * Este método (combo box) permite seleccionar una de las ventas registradas
     *
     * @param evt
     */
    private void cb_VentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_VentaItemStateChanged
        // TODO add your handling code here:
        if (cb_Venta.getSelectedIndex() == 0) {
            return;
        }
        cambiarDatos();
    }//GEN-LAST:event_cb_VentaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_Fecha;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JComboBox<String> cb_Venta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Categoria;
    private javax.swing.JLabel lbl_DNIC;
    private javax.swing.JLabel lbl_DNIV;
    private javax.swing.JLabel lbl_Descripcion;
    private javax.swing.JLabel lbl_Estado;
    private javax.swing.JLabel lbl_Euros;
    private javax.swing.JLabel lbl_FechaP;
    private javax.swing.JLabel lbl_FechaV;
    private javax.swing.JLabel lbl_Foto;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_NC;
    private javax.swing.JLabel lbl_NV;
    private javax.swing.JLabel lbl_NombreP;
    private javax.swing.JLabel lbl_PRODUCTO;
    private javax.swing.JLabel lbl_Precio;
    private javax.swing.JLabel lbl_Ubicacion;
    private javax.swing.JRadioButton rb_Fecha;
    private javax.swing.JRadioButton rb_Historico;
    private javax.swing.JTextArea ta_Descripcion;
    private javax.swing.JTextField tf_Categoria;
    private javax.swing.JTextField tf_DNIC;
    private javax.swing.JTextField tf_DNIV;
    private javax.swing.JTextField tf_Estado;
    private javax.swing.JTextField tf_Fecha;
    private javax.swing.JTextField tf_FechaP;
    private javax.swing.JTextField tf_FechaV;
    private javax.swing.JTextField tf_NC;
    private javax.swing.JTextField tf_NV;
    private javax.swing.JTextField tf_NombreP;
    private javax.swing.JTextField tf_Precio;
    private javax.swing.JTextField tf_Ubicacion;
    // End of variables declaration//GEN-END:variables

    /**
     * Este método sirve para pasar de fecha String a fecha Date
     *
     * @param fecha
     * @return Devuelve la fecha formateada
     * @throws ParseException
     */
    private static Date Date(String fecha) {
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Date date = null;
        try {
            date = format.parse(fecha);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "El formato de fecha ha de ser: \ndd/mm/aaaa", "Formato de Fecha Erróneo", JOptionPane.ERROR_MESSAGE);
        }

        return date;
    }

    /**
     * Este método comprueba que el formato de la fecha es el correcto
     * ("dd/MM/yyyy")
     *
     * @param fecha
     * @return Devuelve true si el formato es correcto o false si no
     * @throws ParseException
     */
    private static boolean ComprobarFecha(String fecha) {
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            Date date = format.parse(fecha);
            return true;
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "El formato de fecha ha de ser: \ndd/mm/aaaa", "Formato de Fecha Erróneo", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    /**
     * Este método cambia los datos de una venta seleccionada por otra que se
     * acaba de seleccionar
     */
    private void cambiarDatos() {
        Venta venta = buscarVenta();
        Producto producto = venta.getProducto();
        cambiarPersonas(venta);
        cambiarProducto(producto);
    }

    /**
     * Este método muestra los datos del comprador y del vendedor
     *
     * @param venta
     */
    private void cambiarPersonas(Venta venta) {
        tf_NC.setText(venta.nombreComprador);
        tf_NV.setText(venta.nombreVendedor);
        tf_DNIC.setText(venta.DNIComprador);
        tf_DNIV.setText(venta.DNIVendedor);
        tf_FechaV.setText(venta.fechaVenta);
    }

    /**
     * Este método muestra los datos del producto que se ha vendido
     *
     * @param producto
     */
    private void cambiarProducto(Producto producto) {
        tf_NombreP.setText(producto.nombre);
        ta_Descripcion.setText(producto.descripcion);
        tf_Categoria.setText(producto.categoria);
        tf_Estado.setText(producto.condicion);
        tf_Precio.setText(Double.toString(producto.precio));
        tf_FechaP.setText(producto.fecha);
        tf_Ubicacion.setText(producto.ubicacion);
    }

    /**
     * Este método busca una venta específica para controlar quién es el
     * vendedor y quién es el comprador
     *
     * @return Devuelve la venta registrada
     */
    private Venta buscarVenta() {
        Venta venta = null;
        int aux = 0;
        while (aux < Ventas.size()) {
            if (VentasLocal.get(cb_Venta.getSelectedIndex() - 1).DNIComprador == Ventas.get(aux).DNIComprador && VentasLocal.get(cb_Venta.getSelectedIndex() - 1).DNIVendedor == Ventas.get(aux).DNIVendedor) {
                venta = VentasLocal.get(cb_Venta.getSelectedIndex() - 1); //Compara los DNI's (Comprador y Vendedor) de las ventas registradas y, si coinciden, guarda dicha venta
                break;
            }
            aux++;
        }
        return venta;
    }

    /**
     * Este método vacía las cajas de texto
     */
    private void limpiar() {
        tf_NombreP.setText("");
        ta_Descripcion.setText("");
        tf_Categoria.setText("");
        tf_Estado.setText("");
        tf_Precio.setText("");
        tf_FechaP.setText("");
        tf_Ubicacion.setText("");
        tf_NC.setText("");
        tf_NV.setText("");
        tf_DNIC.setText("");
        tf_DNIV.setText("");
        tf_FechaV.setText("");
        while (cb_Venta.getItemCount() > 1) {
            cb_Venta.removeItemAt(1);
        }
    }
}
