/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic_Interface;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javapop.Producto;
import javapop.Cliente;
import javapop.Venta;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel González González - GISI
 */

public class Inicio extends javax.swing.JFrame {

    public static ArrayList<Producto> Productos = new ArrayList();
    public static ArrayList<Cliente> Usuarios = new ArrayList();
    public static ArrayList<Venta> Ventas = new ArrayList();

    public static String RutaUsuarios = "./Ficheros/Usuarios.txt";
    public static String RutaProductos = "./Ficheros/Productos.txt";
    public static String RutaVentas = "./Ficheros/Ventas.txt";

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        Usuarios = readUsers();
        Productos = readProducts();
        Ventas = readSales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoUsuario = new javax.swing.ButtonGroup();
        pnl_SeleccionUsuario = new javax.swing.JPanel();
        btn_Admin = new javax.swing.JRadioButton();
        btn_Usuario = new javax.swing.JRadioButton();
        lbl_TipoUsuario = new javax.swing.JLabel();
        pnl_IniciarSesion = new javax.swing.JPanel();
        tf_Usuario = new javax.swing.JTextField();
        pf_Contrasena = new javax.swing.JPasswordField();
        lbl_Usuario = new javax.swing.JLabel();
        lbl_Contrasena = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        btn_NewUser = new javax.swing.JButton();
        lbl_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaPOP");

        TipoUsuario.add(btn_Admin);
        btn_Admin.setSelected(true);
        btn_Admin.setText("Administrador");

        TipoUsuario.add(btn_Usuario);
        btn_Usuario.setText("Usuario");

        lbl_TipoUsuario.setText("Seleccione el tipo de usuario para entrar:");

        javax.swing.GroupLayout pnl_SeleccionUsuarioLayout = new javax.swing.GroupLayout(pnl_SeleccionUsuario);
        pnl_SeleccionUsuario.setLayout(pnl_SeleccionUsuarioLayout);
        pnl_SeleccionUsuarioLayout.setHorizontalGroup(
            pnl_SeleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SeleccionUsuarioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnl_SeleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_SeleccionUsuarioLayout.createSequentialGroup()
                        .addComponent(btn_Admin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Usuario))
                    .addComponent(lbl_TipoUsuario))
                .addGap(49, 49, 49))
        );

        pnl_SeleccionUsuarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Admin, btn_Usuario});

        pnl_SeleccionUsuarioLayout.setVerticalGroup(
            pnl_SeleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SeleccionUsuarioLayout.createSequentialGroup()
                .addComponent(lbl_TipoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_SeleccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Admin)
                    .addComponent(btn_Usuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_SeleccionUsuarioLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Admin, btn_Usuario});

        lbl_Usuario.setText("Usuario:");

        lbl_Contrasena.setText("Contraseña");

        javax.swing.GroupLayout pnl_IniciarSesionLayout = new javax.swing.GroupLayout(pnl_IniciarSesion);
        pnl_IniciarSesion.setLayout(pnl_IniciarSesionLayout);
        pnl_IniciarSesionLayout.setHorizontalGroup(
            pnl_IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_IniciarSesionLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnl_IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Usuario)
                    .addComponent(lbl_Contrasena)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(pf_Contrasena))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_IniciarSesionLayout.setVerticalGroup(
            pnl_IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_IniciarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lbl_Contrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pf_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_IniciarSesionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pf_Contrasena, tf_Usuario});

        btn_Login.setText("Iniciar Sesión");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        btn_NewUser.setText("Nuevo Usuario");
        btn_NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewUserActionPerformed(evt);
            }
        });

        lbl_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JavaPOP_Logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_SeleccionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_IniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Logo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_NewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(82, 82, 82)
                                .addComponent(btn_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_SeleccionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_NewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método (botón) comprueba el tipo de usuario que va a acceder al sistema y lo lleva a su ventana correspondiente si introduce correctamente el usuario y la contraseña
     * @param evt 
     */
    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        if (TipoUsuario.isSelected(btn_Admin.getModel()) && tf_Usuario.getText().equals("admin@javapop.com") && pf_Contrasena.getText().equals("admin")) { //Si se selecciona admin y coinciden usuario y contraseña 
            MainMenuAdmin menu = new MainMenuAdmin(); //Se abre el menú de admin
            menu.setVisible(true);
            this.setVisible(false);
            return;
        } else if (TipoUsuario.isSelected(btn_Usuario.getModel())) { //Si se selecciona usuario
            int aux = 0;
            while (aux < Usuarios.size()) { //Vamos pasando por un array list con todos los usuarios del sistema
                if (Usuarios.get(aux).correo.contentEquals(tf_Usuario.getText()) && Usuarios.get(aux).clave.contentEquals(pf_Contrasena.getText())) { //Si coinciden usuario y contraseña
                    MainMenuCliente menu = new MainMenuCliente(Usuarios.get(aux)); //Se abre el manú de cliente
                    menu.setVisible(true);
                    this.setVisible(false);
                    return;
                }
                aux++;
            }
        }
        JOptionPane.showMessageDialog(rootPane, "El usuario especificado no existe en nuestra aplicacion. \n Porfavor regístrese para poder acceder", "Error a la hora de entrar", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_LoginActionPerformed

    /**
     * Este método (botón) hace que aparezca una nueva ventana para poder crear un nuevo usuario
     * @param evt 
     */
    private void btn_NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewUserActionPerformed
        // TODO add your handling code here:
        NuevoUsuario menu = new NuevoUsuario(Usuarios);
        menu.setVisible(true);
    }//GEN-LAST:event_btn_NewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TipoUsuario;
    private javax.swing.JRadioButton btn_Admin;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_NewUser;
    private javax.swing.JRadioButton btn_Usuario;
    private javax.swing.JLabel lbl_Contrasena;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_TipoUsuario;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JPasswordField pf_Contrasena;
    private javax.swing.JPanel pnl_IniciarSesion;
    private javax.swing.JPanel pnl_SeleccionUsuario;
    private javax.swing.JTextField tf_Usuario;
    // End of variables declaration//GEN-END:variables

    /**
     * Este método lee los usuarios que hay en la ruta determinada para poder actualizarlos
     * @return Devuelve un array list de los usuarios
     */
    public static ArrayList<Cliente> readUsers() {
        ArrayList<Cliente> al = new ArrayList();
        boolean cont = true;
        //System.out.println("Entro en metodo");
        try {
            //System.out.println("Entro en TRY");
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(RutaUsuarios));
            //System.out.println(ois.readObject());
            while (cont != false) {
                Cliente obj = null;
                try {
                    obj = (Cliente) ois.readObject();
                } catch (IOException | ClassNotFoundException e) {
                    //e.printStackTrace();
                }
                if (obj != null) {
                    al.add(obj);
                } else {
                    cont = false;
                }
            }
        } catch (IOException e) {
            // TODO Auto-generated catch block
        }

        return al;
    }

    /**
     * Este método lee los productos que hay en la ruta determinada para poder actualizarlos
     * @return Devuelve un array list de los productos
     */
    public static ArrayList<Producto> readProducts() {
        ArrayList<Producto> al = new ArrayList();
        boolean cont = true;
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(RutaProductos));
            while (cont != false) {
                Producto obj = null;
                try {
                    obj = (Producto) ois.readObject();
                } catch (IOException | ClassNotFoundException e) {

                }
                if (obj != null) {
                    al.add(obj);
                } else {
                    cont = false;
                }
            }
        } catch (IOException e) {
        }
        return al;
    }

    /**
     * Este método lee las ventas que hay en la ruta determinada para poder actualizarlas
     * @return Devuelve un array list de las ventas
     */
    private ArrayList<Venta> readSales() {
        ArrayList<Venta> al = new ArrayList();
        boolean cont = true;
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(RutaVentas));
            while (cont != false) {
                Venta obj = null;
                try {
                    obj = (Venta) ois.readObject();
                } catch (IOException | ClassNotFoundException e) {

                }
                if (obj != null) {
                    al.add(obj);
                } else {
                    cont = false;
                }
            }
        } catch (IOException e) {
        }
        return al;
    }
}
