/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic_Interface;

import javapop.Cliente;
import javapop.ClienteProfesional;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel González González - GISI
 */
public class MainMenuCliente extends javax.swing.JFrame {

    private static Cliente Cliente;

    

    /**
     * Creates new form MainMenu
     */
    public MainMenuCliente(Cliente Cliente) {
        MainMenuCliente.Cliente = Cliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Logo = new javax.swing.JLabel();
        btn_Premium = new javax.swing.JButton();
        btn_AP = new javax.swing.JButton();
        btn_BP = new javax.swing.JButton();
        btn_Busqueda = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaPOP - Menú cliente");

        lbl_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JavaPOP_Logo.png"))); // NOI18N

        btn_Premium.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Premium.setText("Hazte Premium");
        btn_Premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PremiumActionPerformed(evt);
            }
        });

        btn_AP.setText("Alta Productos");
        btn_AP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_APActionPerformed(evt);
            }
        });

        btn_BP.setText("Baja Productos");
        btn_BP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BPActionPerformed(evt);
            }
        });

        btn_Busqueda.setText("Búsqueda");
        btn_Busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BusquedaActionPerformed(evt);
            }
        });

        btn_Exit.setText("Cerrar Sesión");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(btn_Premium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_AP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_BP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Premium, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_AP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_BP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método (botón) comprueba si el cliente ya es premium (profesional) y, si no lo es, abre una ventana para poder realizar el cambio a cliente profesional
     * @param evt 
     */
    private void btn_PremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PremiumActionPerformed
        // TODO add your handling code here:
        if (Cliente instanceof ClienteProfesional) {
            JOptionPane.showMessageDialog(rootPane, "Usted ya es un Cliente Premium", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ClienteProfesionalPremium menu = new ClienteProfesionalPremium(Cliente);
        menu.setVisible(true);
    }//GEN-LAST:event_btn_PremiumActionPerformed

    /**
     * Este método (botón) abre una ventana para poder dar de alta un producto
     * @param evt 
     */
    private void btn_APActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_APActionPerformed
        // TODO add your handling code here:
        AltaProductos menu = new AltaProductos(Cliente);
        menu.setVisible(true);
    }//GEN-LAST:event_btn_APActionPerformed

    /**
     * Este método (botón) abre una ventana para poder dar de baja un producto
     * @param evt 
     */
    private void btn_BPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BPActionPerformed
        // TODO add your handling code here:
        BajaProductos menu = new BajaProductos(Cliente);
        menu.setVisible(true);
    }//GEN-LAST:event_btn_BPActionPerformed

    /**
     * Este método (botón) abre una ventana para poder realizar una búsqueda
     * @param evt 
     */
    private void btn_BusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BusquedaActionPerformed
        // TODO add your handling code here:
        Busqueda menu = new Busqueda(Cliente);
        menu.setVisible(true);
    }//GEN-LAST:event_btn_BusquedaActionPerformed

    /**
     * Este método (botón) hace que volvamos al menú principal
     * @param evt 
     */
    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Inicio menu = new Inicio();
        menu.setVisible(true);
    }//GEN-LAST:event_btn_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuCliente(Cliente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AP;
    private javax.swing.JButton btn_BP;
    private javax.swing.JButton btn_Busqueda;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Premium;
    private javax.swing.JLabel lbl_Logo;
    // End of variables declaration//GEN-END:variables
    
    public static void setCliente(Cliente Cliente) {
        MainMenuCliente.Cliente = Cliente;
    }
}
